name: Development CI/CD Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  backend:
    runs-on: ubuntu-22.04

    services:
      mysql:
        image: mysql:8.0.3
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      PYTHON_VERSION: "3.12"

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Start mysql server
        run: |
          sudo /etc/init.d/mysql start

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          cd backends
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          coverage run -m pytest

      - name: Generate coverage reports
        run: |
          coverage report -m

      - name: Publish coverage report to coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          cd backend
          docker build -t my_flask_app:dev .

      - name: Start ngrok
        run: |
          ngrok http 5000 &
